package com.xstudio.models.sys;

import java.util.Date;

public class SysMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.id
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.name
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.orders
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    private Integer orders;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.icons
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    private String icons;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.urls
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    private String urls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.parentid
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.isshow
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    private Integer isshow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.authname
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    private String authname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.createtime
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.creator
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.updatetime
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.updator
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    private String updator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.id
     *
     * @return the value of sys_menu.id
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.id
     *
     * @param id the value for sys_menu.id
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.name
     *
     * @return the value of sys_menu.name
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.name
     *
     * @param name the value for sys_menu.name
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.orders
     *
     * @return the value of sys_menu.orders
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    public Integer getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.orders
     *
     * @param orders the value for sys_menu.orders
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    public void setOrders(Integer orders) {
        this.orders = orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.icons
     *
     * @return the value of sys_menu.icons
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    public String getIcons() {
        return icons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.icons
     *
     * @param icons the value for sys_menu.icons
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    public void setIcons(String icons) {
        this.icons = icons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.urls
     *
     * @return the value of sys_menu.urls
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    public String getUrls() {
        return urls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.urls
     *
     * @param urls the value for sys_menu.urls
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    public void setUrls(String urls) {
        this.urls = urls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.parentid
     *
     * @return the value of sys_menu.parentid
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.parentid
     *
     * @param parentid the value for sys_menu.parentid
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.isshow
     *
     * @return the value of sys_menu.isshow
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    public Integer getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.isshow
     *
     * @param isshow the value for sys_menu.isshow
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    public void setIsshow(Integer isshow) {
        this.isshow = isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.authname
     *
     * @return the value of sys_menu.authname
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    public String getAuthname() {
        return authname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.authname
     *
     * @param authname the value for sys_menu.authname
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    public void setAuthname(String authname) {
        this.authname = authname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.createtime
     *
     * @return the value of sys_menu.createtime
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.createtime
     *
     * @param createtime the value for sys_menu.createtime
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.creator
     *
     * @return the value of sys_menu.creator
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.creator
     *
     * @param creator the value for sys_menu.creator
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.updatetime
     *
     * @return the value of sys_menu.updatetime
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.updatetime
     *
     * @param updatetime the value for sys_menu.updatetime
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.updator
     *
     * @return the value of sys_menu.updator
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.updator
     *
     * @param updator the value for sys_menu.updator
     *
     * @mbggenerated Wed May 11 20:58:59 CST 2016
     */
    public void setUpdator(String updator) {
        this.updator = updator;
    }
}