package com.xstudio.models.sys;

public class SysRoleMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu.id
     *
     * @mbggenerated Mon Mar 14 17:23:39 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu.menuid
     *
     * @mbggenerated Mon Mar 14 17:23:39 CST 2016
     */
    private Integer menuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu.roleid
     *
     * @mbggenerated Mon Mar 14 17:23:39 CST 2016
     */
    private Integer roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu.id
     *
     * @return the value of sys_role_menu.id
     *
     * @mbggenerated Mon Mar 14 17:23:39 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu.id
     *
     * @param id the value for sys_role_menu.id
     *
     * @mbggenerated Mon Mar 14 17:23:39 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu.menuid
     *
     * @return the value of sys_role_menu.menuid
     *
     * @mbggenerated Mon Mar 14 17:23:39 CST 2016
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu.menuid
     *
     * @param menuid the value for sys_role_menu.menuid
     *
     * @mbggenerated Mon Mar 14 17:23:39 CST 2016
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu.roleid
     *
     * @return the value of sys_role_menu.roleid
     *
     * @mbggenerated Mon Mar 14 17:23:39 CST 2016
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu.roleid
     *
     * @param roleid the value for sys_role_menu.roleid
     *
     * @mbggenerated Mon Mar 14 17:23:39 CST 2016
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}