package com.xstudio.models.sys;

public class SysRoleUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_user.id
     *
     * @mbggenerated Mon Mar 14 16:58:24 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_user.userid
     *
     * @mbggenerated Mon Mar 14 16:58:24 CST 2016
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_user.roleid
     *
     * @mbggenerated Mon Mar 14 16:58:24 CST 2016
     */
    private Integer roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_user.id
     *
     * @return the value of sys_role_user.id
     *
     * @mbggenerated Mon Mar 14 16:58:24 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_user.id
     *
     * @param id the value for sys_role_user.id
     *
     * @mbggenerated Mon Mar 14 16:58:24 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_user.userid
     *
     * @return the value of sys_role_user.userid
     *
     * @mbggenerated Mon Mar 14 16:58:24 CST 2016
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_user.userid
     *
     * @param userid the value for sys_role_user.userid
     *
     * @mbggenerated Mon Mar 14 16:58:24 CST 2016
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_user.roleid
     *
     * @return the value of sys_role_user.roleid
     *
     * @mbggenerated Mon Mar 14 16:58:24 CST 2016
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_user.roleid
     *
     * @param roleid the value for sys_role_user.roleid
     *
     * @mbggenerated Mon Mar 14 16:58:24 CST 2016
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}