package com.xstudio.models.sys;

public class SysRoleAuth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_auth.id
     *
     * @mbggenerated Fri Apr 29 17:01:42 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_auth.roleid
     *
     * @mbggenerated Fri Apr 29 17:01:42 CST 2016
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_auth.authname
     *
     * @mbggenerated Fri Apr 29 17:01:42 CST 2016
     */
    private String authname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_auth.desc
     *
     * @mbggenerated Fri Apr 29 17:01:42 CST 2016
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_auth.id
     *
     * @return the value of sys_role_auth.id
     *
     * @mbggenerated Fri Apr 29 17:01:42 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_auth.id
     *
     * @param id the value for sys_role_auth.id
     *
     * @mbggenerated Fri Apr 29 17:01:42 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_auth.roleid
     *
     * @return the value of sys_role_auth.roleid
     *
     * @mbggenerated Fri Apr 29 17:01:42 CST 2016
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_auth.roleid
     *
     * @param roleid the value for sys_role_auth.roleid
     *
     * @mbggenerated Fri Apr 29 17:01:42 CST 2016
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_auth.authname
     *
     * @return the value of sys_role_auth.authname
     *
     * @mbggenerated Fri Apr 29 17:01:42 CST 2016
     */
    public String getAuthname() {
        return authname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_auth.authname
     *
     * @param authname the value for sys_role_auth.authname
     *
     * @mbggenerated Fri Apr 29 17:01:42 CST 2016
     */
    public void setAuthname(String authname) {
        this.authname = authname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_auth.desc
     *
     * @return the value of sys_role_auth.desc
     *
     * @mbggenerated Fri Apr 29 17:01:42 CST 2016
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_auth.desc
     *
     * @param desc the value for sys_role_auth.desc
     *
     * @mbggenerated Fri Apr 29 17:01:42 CST 2016
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }
}