package com.xstudio.dao.sys;

import com.xstudio.models.sys.SysRoleAuth;
import com.xstudio.models.sys.SysRoleAuthExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface SysRoleAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbggenerated Fri Apr 29 17:01:42 CST 2016
     */
    int countByExample(SysRoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbggenerated Fri Apr 29 17:01:42 CST 2016
     */
    int deleteByExample(SysRoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbggenerated Fri Apr 29 17:01:42 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbggenerated Fri Apr 29 17:01:42 CST 2016
     */
    int insert(SysRoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbggenerated Fri Apr 29 17:01:42 CST 2016
     */
    int insertSelective(SysRoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbggenerated Fri Apr 29 17:01:42 CST 2016
     */
    List<SysRoleAuth> selectByExample(SysRoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbggenerated Fri Apr 29 17:01:42 CST 2016
     */
    SysRoleAuth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbggenerated Fri Apr 29 17:01:42 CST 2016
     */
    int updateByExampleSelective(@Param("record") SysRoleAuth record, @Param("example") SysRoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbggenerated Fri Apr 29 17:01:42 CST 2016
     */
    int updateByExample(@Param("record") SysRoleAuth record, @Param("example") SysRoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbggenerated Fri Apr 29 17:01:42 CST 2016
     */
    int updateByPrimaryKeySelective(SysRoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbggenerated Fri Apr 29 17:01:42 CST 2016
     */
    int updateByPrimaryKey(SysRoleAuth record);
}